apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-02
  labels:
    name: pod-volume-02
spec:
  containers:
    - name: pod-volume-02
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/teste2"
          name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-disk