apiVersion: v1
kind: Pod
metadata:
  name: db-mysql-2
  labels:
    app: db-mysql-2
spec:
  containers:
    - name: db-mysql-container-2
      image: mysql:8.0
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configmap