apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-01
spec:
  template:
    metadata:
      name: replicaset-01
      labels:
        app: replicaset-01
    spec:
      containers:
        - name: nginx-container
          image: nginx:stable
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: replicaset-01